FROM php:7.0-cli-alpine

COPY ./../.. /usr/src/myapp
WORKDIR /usr/src/myapp

RUN apk --no-cache add curl zip
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer install
