name: Tests

on:
  push:
  pull_request:

jobs:
  build:
    name: Tests PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1']

    steps:
      - uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run test suite
        run: |
          mkdir ./coverage
          php -r 'phpinfo();' > ./coverage/phpinfo.txt
          ./vendor/bin/phpunit --version > ./coverage/phpunit-version.txt
          ./vendor/bin/phpunit --configuration ./phpunit-${{ matrix.php-version }}.xml --coverage-clover ./coverage/coverage.clover --coverage-html ./coverage/html/

      - name: Save coverage results
        uses: actions/upload-artifact@v3
        with:
          name: coverage-php${{ matrix.php-version }}
          path: ./coverage/
