name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    # “At 17:45 on Friday.”
    - cron:  '45 17 * * 5'

jobs:
  build:
    name: Tests PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2']

    steps:
      - uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run test suite
        run: |
          mkdir -p ./coverage/php-${{ matrix.php-version }}
          ./vendor/bin/phpunit --configuration ./phpunit-${{ matrix.php-version }}.xml --coverage-clover ./coverage/php-${{ matrix.php-version }}/coverage.clover --coverage-html ./coverage/php-${{ matrix.php-version }}/html/

      - name: Get current date/time
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d-%H%M')"

      - name: Save coverage results
        uses: actions/upload-artifact@v3
        with:
          name: coverage_php-array-to-xml_${{ steps.date.outputs.date }}
          path: ./coverage
